### PR TITLE
Validate Binary Search Tree

### PR DESCRIPTION
**Pull request by lxieyang**
The previous version will cause wrong answer. The current version fixed that issue. Comparator used.

### CODE REVIEW

**Comment by soulmachine** [comment]
Hi, my code is much shorter than yours, and it can also pass all test cases. Why do we need to change the code?

**Comment by lxieyang** [comment]
Hi. I double checked the original code. It seems that it's not passing one of the long test cases. Would you check again? Correct me if I'm wrong plz.

**Comment by soulmachine** [comment]
I submitted my code a few seconds ago, and it accepted.

**Comment by lxieyang** [comment]
I’ve attached the resulting webpage. Is there a problem with the inconsistency?

**Comment by soulmachine** [comment]
I'm sorry, my code in my computer is newer than Github, the code on Github has a problem, I just modified one line and pushed to Github, it should work now

**Comment by lxieyang** [comment]
Would you also compile the tex file so that the pdf is up-to-date. If there’s any chance, could you also include my version to the tex? I thought it was more clear in terms of thought flow: get the inorder traversal values and then check if valid.

**Comment by soulmachine** [comment]
I will update the PDF, but in this case, your code is also recursive but much verbose than mine, there is no value to adopt your code, thanks

**Pull request closed without merging**
